//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHyphenator {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Patterns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Patterns() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NHyphenator.Patterns", typeof(Patterns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sil-ben-tren-nung ähnelt.
        /// </summary>
        internal static string hyph_de_1901_hyp {
            get {
                return ResourceManager.GetString("hyph_de_1901_hyp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .ab1a
        ///.ab3l
        ///.abo2
        ///.ab3ol
        ///.ab1or
        ///.ab3s2
        ///.ab3u
        ///.ade3n
        ///.aft2
        ///.ag2a
        ///.ago1
        ///.ag4r
        ///.ag2u
        ///.ai2s
        ///.akt2a
        ///.al2e
        ///.ale3u2
        ///.al3lei
        ///.al3len
        ///.al3lo3
        ///.al3se
        ///.al2tei
        ///.al2tel
        ///.al4terp
        ///.alter4s3
        ///.al2tra
        ///.al2tu
        ///.ampe4
        ///.amt2s1
        ///.ana1c
        ///.an4a3t
        ///.an3d2
        ///.anden4k
        ///.and4ri
        ///.an1e
        ///.ang2
        ///.an3gli
        ///.an3go
        ///.ang4s4
        ///.angst3
        ///.ani2s
        ///.an3k4
        ///.an3s2
        ///.an4si.
        ///.an2tar
        ///.an3z4
        ///.ap3p4le.
        ///.ari1
        ///.ar3k2a
        ///.ar2m3ac
        ///.ar4mun
        ///.ar2sc
        ///.ar4t3ei
        ///.arter2
        ///.ar4t3erh
        ///.ar2t1r
        ///.arz2
        ///.as2b
        ///.as2ko
        ///.as4sest
        ///.as4t
        ///.as2zen
        ///.ata1
        ///.at2h
        ///.au3d
        ///.au4f3
        ///.au6fac
        ///.aufs4
        ///.au2s1
        ///.aussen6d [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string hyph_de_1901_pat {
            get {
                return ResourceManager.GetString("hyph_de_1901_pat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sil-ben-tren-nung
        /// ähnelt.
        /// </summary>
        internal static string hyph_de_1996_hyp {
            get {
                return ResourceManager.GetString("hyph_de_1996_hyp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .ab1a
        ///.ab3l
        ///.abo2
        ///.ab3ol
        ///.ab1or
        ///.abs2
        ///.ab3si
        ///.ab3u
        ///.ach2sp
        ///.ade3n
        ///.ae3
        ///.aft2
        ///.ago1
        ///.ag4r
        ///.ag2u
        ///.ai2s
        ///.akt2a
        ///.al2e
        ///.ale3u4
        ///.al3lei
        ///.al3len
        ///.al3li
        ///.al3se
        ///.al4st
        ///.al2tei
        ///.al4tel
        ///.al4terp
        ///.alter4s3
        ///.al2tra
        ///.alt3s4
        ///.al2tu
        ///.ampe4
        ///.amt2s1
        ///.ana1c
        ///.an4a3t
        ///.an3d2
        ///.anden4k
        ///.an1e
        ///.ang2
        ///.an3g4li
        ///.an3go
        ///.angs4
        ///.angst3
        ///.ani2s
        ///.an3k4
        ///.an3s2
        ///.an4si.
        ///.an2tar
        ///.an3z4
        ///.ap3p4le.
        ///.ari1e
        ///.ar3k2a
        ///.ar2m3ac
        ///.ar4mun
        ///.ar2sc
        ///.ar2tan
        ///.ar4t3ei
        ///.ar4t3erh
        ///.ar2t1r
        ///.arz2
        ///.as4b
        ///.asbe2
        ///.as2ko
        ///.as3ta
        ///.as4ta.
        ///.as4tat
        ///.as3tr
        ///.as2zen
        ///.ata1
        ///.at2h
        ///.a [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string hyph_de_1996_pat {
            get {
                return ResourceManager.GetString("hyph_de_1996.pat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die uni-ver-sity
        ///uni-ver-sit-ies
        ///how-ever
        ///ma-nu-script
        ///ma-nu-scripts
        ///re-ci-pro-city
        ///through-out
        ///some-thing
        /// ähnelt.
        /// </summary>
        internal static string hyph_en_gb_hyp {
            get {
                return ResourceManager.GetString("hyph_en_gb_hyp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .ab4i
        ///.ab3ol
        ///.ace4
        ///.acet3
        ///.ach4
        ///.ac5tiva
        ///.ad4din
        ///.ad3e
        ///.ad3o
        ///.ae5d
        ///.aer3i
        ///.af3f
        ///.af3t
        ///.ag4a
        ///.ag5n
        ///.air3
        ///.al5im
        ///.al1k
        ///.al3le
        ///.am5ar
        ///.ama5te
        ///.am2i
        ///.am3pe
        ///.am3ph
        ///.an1
        ///.ana3b
        ///.ana3s
        ///.and2
        ///.an5da
        ///.an4el
        ///.an4en
        ///.an4gl
        ///.an4on.
        ///.an3s
        ///.ant3a
        ///.an3ti3
        ///.ant4ic
        ///.an4t5o
        ///.any5
        ///.aph5or
        ///.ap4i
        ///.ar5ab
        ///.ar5ap
        ///.ar4ci
        ///.ar5d
        ///.ar4e
        ///.ari4
        ///.ar4ise
        ///.ar4isi
        ///.ar5sen
        ///.art5icl
        ///.as1
        ///.as4q
        ///.as5sib
        ///.at5ar
        ///.ateli4
        ///.at5omise
        ///.at5omiz
        ///.at3r
        ///.at3t
        ///.au3b
        ///.au3g4u
        ///.aur4e5
        ///.aus5
        ///.authe [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string hyph_en_gb_pat {
            get {
                return ResourceManager.GetString("hyph_en_gb_pat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die as-so-ciate
        ///as-so-ciates
        ///dec-li-na-tion
        ///oblig-a-tory
        ///phil-an-thropic
        ///present
        ///presents
        ///project
        ///projects
        ///reci-procity
        ///re-cog-ni-zance
        ///ref-or-ma-tion
        ///ret-ri-bu-tion
        ///ta-ble
        /// ähnelt.
        /// </summary>
        internal static string hyph_en_us_hyp {
            get {
                return ResourceManager.GetString("hyph_en_us_hyp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .ach4
        ///.ad4der
        ///.af1t
        ///.al3t
        ///.am5at
        ///.an5c
        ///.ang4
        ///.ani5m
        ///.ant4
        ///.an3te
        ///.anti5s
        ///.ar5s
        ///.ar4tie
        ///.ar4ty
        ///.as3c
        ///.as1p
        ///.as1s
        ///.aster5
        ///.atom5
        ///.au1d
        ///.av4i
        ///.awn4
        ///.ba4g
        ///.ba5na
        ///.bas4e
        ///.ber4
        ///.be5ra
        ///.be3sm
        ///.be5sto
        ///.bri2
        ///.but4ti
        ///.cam4pe
        ///.can5c
        ///.capa5b
        ///.car5ol
        ///.ca4t
        ///.ce4la
        ///.ch4
        ///.chill5i
        ///.ci2
        ///.cit5r
        ///.co3e
        ///.co4r
        ///.cor5ner
        ///.de4moi
        ///.de3o
        ///.de3ra
        ///.de3ri
        ///.des4c
        ///.dictio5
        ///.do4t
        ///.du4c
        ///.dumb5
        ///.earth5
        ///.eas3i
        ///.eb4
        ///.eer4
        ///.eg2
        ///.el5d
        ///.el3em
        ///.enam3
        ///.en3g
        ///.en3s
        ///.eq5ui5t
        ///.er4ri
        ///.es3
        ///. [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string hyph_en_us_pat {
            get {
                return ResourceManager.GetString("hyph_en_us_pat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ас-бест
        ///бездн
        ///биз-нес-мен
        ///буй-нак-ске
        ///вбли-зи
        ///взба-ла-муть-ся
        ///вздрем-нешь
        ///во-до-сли-вом
        ///волж-ске
        ///воп-лем
        ///вопль
        ///вост-ра
        ///во-ткать
        ///во-ткем
        ///во-ткешь
        ///во-тку
        ///во-ткут
        ///впол-обо-ро-та
        ///впол-уха
        ///все-во-лож-ске
        ///вцспс
        ///га-рем-но-го
        ///го-ло-дра-нец
        ///грэс
        ///дву-зу-бец
        ///днепр
        ///добре-ем
        ///до-бре-ем-ся
        ///добре-ет
        ///добре-е-те
        ///до-бре-е-тесь
        ///до-бре-ет-ся
        ///добре-ешь
        ///до-бре-ешь-ся
        ///добрею
        ///до-бре-юсь
        ///добре-ют
        ///до-бре-ют-ся
        ///до-бре-сти
        ///до-бро-дят
        ///до-брось
        ///до-брось-те
        ///до-бро-сят
        ///до-бро-шу
        ///домну
        ///доп-пель
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string hyph_ru_hyp {
            get {
                return ResourceManager.GetString("hyph_ru_hyp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .аб1р
        ///.аг1ро
        ///.ади2
        ///.аи2
        ///.ак1р
        ///.аль3я
        ///.ар2т1о2
        ///.ас1то
        ///.аст1р
        ///.ау2
        ///.би2о
        ///.во2б3л
        ///.во3ж2д
        ///.го2ф
        ///.дек2
        ///.де1кв
        ///.ди2ак
        ///.ди1о
        ///.до3п
        ///.до3т2
        ///.епи3
        ///.зав2р
        ///.за3м2н
        ///.за3п
        ///.иг1р
        ///.изг2
        ///.из3н
        ///.ии2
        ///.ик1р
        ///.ио2
        ///.ио4на
        ///.ис3
        ///.ле2о
        ///.ле2п3р
        ///.лес1к
        ///.ль2
        ///.люст1
        ///.ме2ж1у2
        ///.ми1ом
        ///.мо2к1
        ///.му2шт1
        ///.на1в
        ///.на3т
        ///.на3ш2
        ///.не3вн
        ///.не1др
        ///.не1з2
        ///.не1сл
        ///.не1с2ц
        ///.не3т
        ///.нос1к
        ///.нук1л
        ///.обо3ж2
        ///.ово1
        ///.ог3н
        ///.оз4
        ///.ос2ка
        ///.ос2п
        ///.ос3пи
        ///.от1в
        ///.от1ро
        ///.от1ру
        ///.от1уж
        ///.по3в2
        ///.по3ж2
        ///.поз2н
        ///.прос2
        ///. [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string hyph_ru_pat {
            get {
                return ResourceManager.GetString("hyph_ru_pat", resourceCulture);
            }
        }
    }
}
